//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skud
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShifts
    {
        public int Id { get; set; }
        public long CardUid { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> LeavingTime { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
